/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path="./core.d.ts" />
/// <reference path="./csm.d.ts" />
/// <reference path="./gltf.d.ts" />
/// <reference path="./input.d.ts" />
/// <reference path="./orbit.d.ts" />
/// <reference path="./physics.d.ts" />
/// <reference path="./player.d.ts" />
/// <reference path="./portal.d.ts" />
/// <reference path="./postprocessing.d.ts" />
/// <reference path="./render.d.ts" />
/// <reference path="./scene.d.ts" />
/// <reference path="./text.d.ts" />
/// <reference path="./transform.d.ts" />
/// <reference path="./utils.d.ts" />
/// <reference path="./vrm.d.ts" />
